### ISSUE TITLE
Check thành viên nhóm đã đủ chưa nha

### ISSUE THREAD

**Issue by trthann** [trthann/L-p-10A06---Nh-m-02#1]
alo mng ơiii

**Comment by YDinhC06** [comment]
À tui thấy An rồiiiiiii

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Thầy có dzợ chưa z :))

**Comment by duyanhthptphunhuan** [comment]
xin chaoooo mng

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
สวัสดีครับ ผมชือDũngนะครับ

**Comment by trthann** [comment]
你好

**Comment by trthann** [comment]
các bạn có thấy cái project tui tạo hong za

**Comment by HienCaoPhuNhuan** [comment]
@trthann oke gút chóp, con chỉ các nhóm khác nữa nha

**Comment by HienCaoPhuNhuan** [comment]
> Thầy có dzợ chưa z :))

Bí mật

**Comment by trthann** [comment]
@HienCaoPhuNhuan thầy khen quài...con thích z =))))

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
@HienCaoPhuNhuan thầy trả lời trên đây đâu ai biết âu thầy !!

**Comment by trthann** [comment]
@HienCaoPhuNhuan  ơ kìa thầy

**Comment by trthann** [comment]
@HienCaoPhuNhuan  k khen là giận, nghỉ khoẻ nun ạ

**Comment by HienCaoPhuNhuan** [comment]
> @HienCaoPhuNhuan  k khen là giận, nghỉ khoẻ nun ạ

Điểm con nằm trong tay thầy

**Comment by trthann** [comment]
@HienCaoPhuNhuan  "hăm doạ hả" - của...

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Hổng khen nó bơ thầy luôn đó thầy. Thầy hong sợ bị bơ hở thầyyyy

**Comment by trthann** [comment]
@HienCaoPhuNhuan  thầy ít có ác 💔

**Comment by HienCaoPhuNhuan** [comment]
> > > @HienCaoPhuNhuan nó hong lấy thì thầy chuyển qua con nha thầy con nhận hết á con hong có ngại âu 😌
> > 
> > Tối rồi, mình đi ngủ đi con
> 
> Mai Shopee, Lazada sale mà thầy sao mà ngủ đượcccc 👀

Đừng có ngủ quên qua bài 15ph nha

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
> > > > @HienCaoPhuNhuan nó hong lấy thì thầy chuyển qua con nha thầy con nhận hết á con hong có ngại âu 😌
> > > 
> > > 
> > > Tối rồi, mình đi ngủ đi con
> > 
> > 
> > Mai Shopee, Lazada sale mà thầy sao mà ngủ đượcccc 👀
> 
> Đừng có ngủ quên qua bài 15ph nha

Thầy đừng nói xui zậy chớ thầy 😢😢

**Comment by duyanhthptphunhuan** [comment]
coi chừng đúng thiệt đó thầy ơi

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HienCaoPhuNhuan** [comment]
Mấy đứa ngủ trễ ghê

**Comment by duyanhthptphunhuan** [comment]
lo săn sale á thầy

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
