### ISSUE TITLE
THẢO LUẬN CÂU HỎI TÌM HIỂU Bài 7 và 8

### ISSUE THREAD

**Issue by trthann** [trthann/L-p-10A06---Nh-m-02#10]

**Comment by YDinhC06** [comment]
T làm câu 1,3 b7 nhee

**Comment by duyanhthptphunhuan** [comment]
t làm câu 1 2 bài 8 nhá

**Comment by PhuongNgannLe** [comment]
t làm câu 1 bài 7 với câu 2 bài 8 nhaaa

**Comment by trthann** [comment]
cóa gì hong hĩu thì nhắn nho, t giúp choa

**Comment by trthann** [comment]
Dũng làm c2 bài 7 với c3 bài 8 nha

**Comment by trthann** [comment]
mng ơi, cố gắng làm đến t4 tuần này nha

**Comment by trthann** [comment]
lo làm đi nha, có gì khó hay hong hĩu thì nhắn t

**Comment by trthann** [comment]
chịu khó đẩy nhanh tốc độ lên nha

**Comment by YDinhC06** [comment]
Okeeeee

**Comment by trthann** [comment]
cái chỗ câu 1 bài 8, mng nhớ tìm nhìu cái ứng dụng lên nha

**Comment by trthann** [comment]
thầy Hiền Cao "đệp troai" mong chờ lắm đóaâ

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Hế nhô mng

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Tui làm c1 bài 7 với c2 bài 8 nhe

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
> Dũng làm c2 bài 7 với c3 bài 8 nha

Dạ

**Comment by trthann** [comment]
có gì k bít làm hay k kịp thì nhắn nhó

**Comment by trthann** [comment]
à để làm c3 bài 8 tốt hơn thì mng nên thử hai cái mà bữa thầy Hiền share tuần trước nhen

**Comment by PhuongNgannLe** [comment]
Câu 1 Bài 7:
Khi thực hiện một phần mềm ứng dụng mà không có hệ điều hành thì không thể thực hiện được bởi vì nhờ hệ điều hành ta mới có thể giao tiếp được với máy, mới viết được những phần mềm máy tính.
Câu 2 Bài 8:
Một số lĩnh vực mà tin học khó có thể sử dụng được là :
- Khám chữa bệnh: Tin học hay cụ thể là trí tuệ nhân tạo vẫn chưa thể thay thế đội ngũ y bác sỹ trong việc khám bệnh cho con người.
- Tâm lí con người: Cảm xúc của con người rất phức tạp và máy móc chưa thể đủ dữ liệu để phân tích trạng thái tình cảm.

**Comment by duyanhthptphunhuan** [comment]
Câu 1 bài 8 
-Một số ứng dụng của tin học
+Giải các bài toán khoa học kĩ thuật
+Hỗ trợ việc quản lý
+Tự động hóa và điều khiển
+Truyền thông
+Soạn thảo, in ấn, văn phòng
+Trí tuệ nhân tạo
+Giáo Dục
+Giải trí
-Ứng dụng yêu thích nhất là:
+Giáo Dục
+Vì trong thời đại dịch bệnh này việc học tập qua mạng internet nói chung và các phần mềm được thiết kế nhằm giúp cho phương pháp giảng dạy của giáo viên và việc học hành của học sinh nói riêng bỗng trở thành sự ưu tiên giúp học sinh có thể tiếp thu kiến thức mà không cần phải đến trường.
Cre loigiaihay.com
Câu 2 bài 8 
Một số lĩnh vực mà Tin học khó có thể ứng dụng được là :
- Khám chữa bệnh: Tin học hay cụ thể là trí tuệ nhân tạo vẫn chưa thể thay thế đội ngũ y bác sĩ trong việc khám bệnh cho con người.
- Tâm lí con người: Cảm xúc của con người rất phức tạp và máy móc chưa thể đủ dữ liệu để phân tích trạng thái tình cảm.
Cre loigiaihay.com

**Comment by trthann** [comment]
nhóm đỉnh qá nhóm ơiii

**Comment by trthann** [comment]
iu nhóm qá ạ, cảm ơn zì sự tích cực này gất nhìu

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 2 bài 7 á mng làm sao z

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Tui chỉ biết nó là có thể thôi à

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Còn ví dụ hay vì sao thì coi trên youtube hay google nó hong chỉ luôn á

**Comment by trthann** [comment]
để t cầu cứu thầy hjuhju

**Comment by HienCaoPhuNhuan** [comment]
> Câu 2 bài 7 á mng làm sao z

nghĩa là ví dụ với hệ điều hành Windows, nếu các ứng dụng có thể cài đặt và sử dụng trên windows thì có thể giống như vậy trên hệ điều hành khác ko (ví dụ như MacOS, Linux)

**Comment by trthann** [comment]
https://docs.google.com/document/d/1w85Wla4CGx0Tvl_tzIe3kP3ig7vtfCofkBjlW87lOOk/edit

mng vô link này nkaaaa

**Comment by trthann** [comment]
nhắn nhủ những tâm tình của mình dành choa thầy đókk

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
> > Câu 2 bài 7 á mng làm sao z
> 
> nghĩa là ví dụ với hệ điều hành Windows, nếu các ứng dụng có thể cài đặt và sử dụng trên windows thì có thể giống như vậy trên hệ điều hành khác ko (ví dụ như Mth

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
> > Câu 2 bài 7 á mng làm sao z
> 
> nghĩa là ví dụ với hệ điều hành Windows, nếu các ứng dụng có thể cài đặt và sử dụng trên windows thì có thể giống như vậy trên hệ điều hành khác ko (ví dụ như MacOS, Linux)

Thầy có gợi ý nào về cái câu tại sao nó có thể cài đặt và sử dụng trên hệ điều hành khác được hong thầyyyy

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 2 bài 7 : 
- Đa số ứng dụng có thể được cài đặt trên hệ điều hành này vẫn có thể cài đặt trên các hệ điều hành khác vì các ứng dụng đó được thiết kế để có thể sử dụng trên nhiều nền tảng và hệ điều hành nhằm đáp ứng cho nhu cầu của người sử dụng, cũng như không để những người dùng hệ điều hành khác nhau gặp những khó khăn, thiệt thòi khi sử dụng ứng dụng của họ.
    • Ví dụ : Google có thể sử dụng được trên nhiều hệ điều hành khác nhau ( Android, iOS, Window, ... )
- Tuy nhiên cũng có những ứng dụng được cài đặt trên hệ điều hành này không thể cài đặt trên hệ điều hành khác. Bởi vì có 1 số ứng dụng chỉ độc quyền mỗi hệ điều hành đó có và không thể sử dụng trên các hệ điều hành khác.
   • Ví dụ : Apple music chỉ có thể cài đặt trên hệ điều hành iOS chứ không thể cài đặt trên hệ điều hành Android, ... được.

**Comment by trthann** [comment]
mng ráng tìm thêm ứng dụng tin học mà tụi mình làm được nha

**Comment by YDinhC06** [comment]
Ứng dụng tin học
https://docs.google.com/forms/d/1wpVfAYGRRT-vo0zBaz4lAN69_Upa6THKIU5ewkqXDMo/viewform?edit_requested=true

**Comment by trthann** [comment]
cta tiếp tục làm bài 9 và 10 nhen, qua issue bài 9 và 10i nha, t có tạo r áaa

**Comment by trthann** [comment]
à tạo poster i mng, thấy dễ nè

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
> à tạo poster i mng, thấy dễ nè

Poster là s á

**Comment by trthann** [comment]
[![image](https://user-images.githubusercontent.com/92015571/142424815-20aad3e5-259d-45ec-a247-5b8a2479ce86.png)
](https://www.google.com/search?q=poster&tbm=isch&source=iu&ictx=1&fir=jomYrHB2Gc9-nM%252CByVnp7SyLtX75M%252C_%253BBf12sKstKmjzCM%252ClvxKbozY0vmDsM%252C_%253B8Sad7TLiJsN56M%252CAoDaCNrR2iLZeM%252C_%253BK7lL_7Wi5awxSM%252CAoDaCNrR2iLZeM%252C_%253B3TDgpMn174Ua5M%252CO3sXLGhwVlgTfM%252C_%253BVdv2n5UhTw14aM%252CByVnp7SyLtX75M%252C_%253BRcnQwJrsi4qFbM%252CVJS9N6ghDMJMQM%252C_%253BaKYJ-QWosbDURM%252CU3AmQSgJ0aqNkM%252C_%253BJRwtrcntYcahmM%252CQpxl-u9mGUjQSM%252C_%253BGBvKTnwZbObDqM%252CWictLmMVdkhjVM%252C_%253BwSQdfKk4ywm_aM%252CByVnp7SyLtX75M%252C_%253BV6pEEVBNHX9fiM%252CO03GOGa3Imy4rM%252C_%253B4lL6jupZsbVCMM%252CWictLmMVdkhjVM%252C_&vet=1&usg=AI4_-kTsWCDBGN8w6cfrQQjkzUzX_ThzrQ&sa=X&ved=2ahUKEwjwvY6Yg6L0AhU3sFYBHc-CAbcQ9QF6BAgGEAE&biw=1920&bih=912&dpr=1#imgrc=jomYrHB2Gc9-nM)

**Comment by trthann** [comment]
giống z á

**Comment by YDinhC06** [comment]
Mn t có làm cái poster rồi nè nma k gửi ảnh lên đây đc nên t gửi mess đỡ nhaaa
