### ISSUE TITLE
THẢO LUẬN CÂU HỎI TÌM HIỂU bài 9 và bài 10

### ISSUE THREAD

**Issue by trthann** [trthann/L-p-10A06---Nh-m-02#11]
bài cúi cùn ùi, nhớ làm cho thiệt là tút để thầy Hiền có cái đọc cho zui nha mng

**Comment by YDinhC06** [comment]
Okeeee

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
> bài cúi cùn ùi, nhớ làm cho thiệt là tút để thầy Hiền có cái đọc cho zui nha mng

Otee

**Comment by trthann** [comment]
@duyanhthptphunhuan @PhuongNgannLe

**Comment by trthann** [comment]
vào chọn câu đi nha

**Comment by trthann** [comment]
![image](https://user-images.githubusercontent.com/92015571/142709280-5bcfa70c-2583-43ad-bed7-adbbb7e9abe8.png)

**Comment by duyanhthptphunhuan** [comment]
t làm câu 1 2 bài 10 nhé mng

**Comment by YDinhC06** [comment]
t làm c3 b9, c1 b10 nhoaaa

**Comment by PhuongNgannLe** [comment]
t làm câu 2 bài 9 với câu 2 bài 10 nheeee

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
T làm câu 3 bài 9 với câu 2 bài 10 nha

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 2 bài 10 : - Hệ điều hành thường được lưu trữ ở bộ nhớ ngoài ( đĩa cứng, CD, ... ).
                         - Để khởi động máy, hay để máy tính có thể hoạt động, nhất thiết phải cần hệ điều hành. Công đoạn nạp hệ điều hành hiểu đơn giản là cách “đánh thức” hệ điều hành, làm chiếc máy tính của bạn hoạt động.

**Comment by YDinhC06** [comment]
Câu 1 Bài 10
     •Hệ điều hành (Operating System – viết tắt: OS) là tập hợp các chương trình được tổ chức thành 1 hệ thống với nhiệm vụ đảm bảo tương tác giữa người dùng với máy tính, cung cấp các phương tiện và dịch vụ để điều phối thực hiện các chương trình quản lí chặt chẽ các tài nguyên của máy, tổ chức khai thác thuận tiện 1 cách tối ưu.
  
  •Hệ điều hành có 3 loại chính:
– Hệ điều hành đơn nhiệm 1 người dùng;
– Hệ điều hành đa nhiệm 1 người dùng;
– Hệ điều hành đa nhiệm nhiều người dùng.

Cre: sgk Tin học (tr 62,63)

**Comment by YDinhC06** [comment]
Câu 1 Bài 9 
Ứng dụng tin học đối với bản thân trong việc học:
+ Lên Google tìm kiếm những thông tin chưa hiểu rõ.
+ Lên youtube xem những video giảng bài của giáo viên khác để nắm rõ bài hơn.
+ Lên mạng xã hội tham gia vào các nhóm để có thêm nhiều kiến thức mới bên ngoài lớp học.

**Comment by YDinhC06** [comment]
Câu 3 Bài 9
•Thông tin cá nhân rất quan trọng
•Một số trường hợp thông tin sẽ bị kẻ xấu sử dụng:                                                     
-Người dùng có thể truy cập nhầm các đường dẫn cài phần mềm độc hại bị lừa đánh cắp dữ liệu cá nhân.
-Nhập thông tin cá nhân vào các trang web không bảo mật dẫn đến lộ các thông tin quan trọng như: số CCCD, tài khoản ngân hàng🏦,.....

•Cách khắc phục, bảo vệ:
-Tuyệt đối không nhấp vào những đường dẫn không rõ ràng.
-Không nhập thông tin cá nhân vào các trang web không bảo mật.🔒
-Không chia sẻ thông tin, hình ảnh nhạy cảm lên mạng xã hội.

**Comment by duyanhthptphunhuan** [comment]
Câu 1 Bài 10
-Hệ điều hành ( Operating System) viết tắt: OS là tập hợp các chương trình được tổ chức thành một hệ thống với nhiệm vụ:
+ Đảm bảo tương tác giữa người dùng với máy tính.
+ Cung cấp các phương tiện và dịch vụ để điều phối thực hiện chương trình.
+ Quản lí chặt chẽ các tài nguyên của máy, tổ chức khai thác chúng một cách thuận tiện và tối ưu.
-Hệ điều hành có 3 loại chính là:
+Đơn nhiệm một người dùng
+ Đa nhiệm một người dùng
+Đa nhiệm nhiều người dùng
Câu 2 Bài 10 
-Hệ điều hành thường được lưu trữ dưới dạng các môđun độc lập trên bộ nhớ ngoài (đĩa cứng, đĩa mềm, CD,  các loại trống từ, băng từ,...)
-Phải nạp hệ điều hành vào máy tính thì máy mới hoạt động được là bởi vì hệ điều hành là chương trình điều khiển mọi hoạt động trong máy tính, đóng vai trò trung gian trong việc giao tiếp giữa người sử dụng và phần cứng máy tính nên khi không cài hệ điều hành thì mọi thao tác trên máy tính đều rất khó khăn. Vì vậy hệ điều hành phải được cài đặt đầu tiên trên máy tính.

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 3 bài 9 :
- Thông tin cá nhân của bản thân rất quan trọng.
- "Vẽ" ra tình huống : 
  Một sáng ngủ dậy thấy mình bị mất facebook. Nhớ lại thì đã truy cập đường link nhận quà trong game.
- Cách khắc phục, bảo vệ : 
  + Tránh truy cấp các trang web đen, không rõ ràng.
  + Không tự ý giao mật khẩu facebook, tài khoản ngân hàng, CCCD, ... cho ai khác.
  + Lập 1 số biện pháp bảo vệ chặt chẽ ví dụ như lập 2 lớp bảo vệ cho tài khoản của chính mình hay dùng FaceID, ...

**Comment by trthann** [comment]
câu 1 bài 9 là mỗi người nêu ra một ý á nha

**Comment by trthann** [comment]
theo tui thì ứng dụng tin học của bản thân là tạo được mã QR, các đường link phục vụ cho học tập như GG Meet, GG Docs,..

**Comment by PhuongNgannLe** [comment]
Câu 2 Bài 9 :
Câu 2 bài 9
Theo em, những xu hướng sử dụng công nghệ hiện tại phù hợp tất cả với suy nghĩ, sự vận hành của xã hội
5 ví dụ :
-Đầu tiên là trí tuệ nhân tạo Al
-Thiết bị dụng cụ công nghệ áp dụng vào cuộc sống hằng ngày như máy hút bụi rửa chén...
-Phương tiện vận chuyển thông minh
-Công nghệ chăm sóc sức khỏe từ xa
-Mạng 5G
Theo em, nhưng sản phẩm và xu hướng sử dụng công nghệ hiện nay rất tiện lợi và thông minh vì vậy nên giữ nguyên và phát triển chúng.

**Comment by PhuongNgannLe** [comment]
Câu 2 Bài 10 :
Hệ điều hành thường được lưu trữ dưới dạng các môđun độc lập trên bộ nhớ ngoài (Đĩa cứng, đĩa mềm, CD...).
Một máy tính nếu không có hệ điều hành thì hầu như không thể sử dụng được. Vì hệ điều hành điều khiển mọi hoạt động của máy tính, giúp việc sử dụng máy tính trở nên đơn giản, dễ dàng và hiệu quả hơn rất nhiều.

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 1 bài 9 :
Ngoài việc học tập thì ta có thể dựa vào Tin học để giải trí sau giờ học với những trò chơi. Hay ta có thể gửi những lời chúc thân thương tới bạn bè, người thân, đồng nghiệp, ... mà ta ngại khó nói thành lời.

**Comment by PhuongNgannLe** [comment]
Câu 2 Bài 9 :
Theo mình nghĩ những xu hướng sử dụng công nghệ hiện tại phù hợp tất cả với suy nghĩ, sự vận hành của xã hội
5 ví dụ :
-Trí tuệ nhân tạo Al
-Thiết bị dụng cụ công nghệ áp dụng vào cuộc sống hằng ngày như máy hút bụi rửa chén...
-Phương tiện vận chuyển thông minh
-Công nghệ chăm sóc sức khỏe từ xa
-Mạng 5G
Theo mình, những sản phẩm và xu hướng sử dụng công nghệ hiện nay rất tiện lợi và thông minh vì vậy nên giữ nguyên và phát triển chúng.

**Comment by duyanhthptphunhuan** [comment]
Câu 1 Bài 9
-Ứng dụng của tin học đối với bản thân trong việc học tập:
+Tham gia các nhóm học tập giao lưu học hỏi với mọi người trên mạng xã hội.
+Có thể giải lao bằng cách chơi game, nghe nhạc để giải trí sau những giờ học căng thẳng.
+Có thể lên youtube coi lại những bài giảng nếu chưa hiểu kịp trong giờ học.

**Comment by PhuongNgannLe** [comment]
Sự ứng dụng của tin học của bản thân trong việc học, làm việc trong cuộc sống :
-Giao lưu, trò chuyện với bạn bè và người thân
-Giúp đỡ chúng ta trong việc học online
-Giải trí sau giờ học và làm việc: đọc báo, nghe nhạc, xem phim...
