### ISSUE TITLE
THẢO LUẬN CÂU HỎI TÌM HIỂU Bài 5 và Bài 6

### ISSUE THREAD

**Issue by trthann** [trthann/L-p-10A06---Nh-m-02#6]

**Comment by trthann** [comment]
hiiii mng

**Comment by PhuongNgannLe** [comment]
xin ckao mọi ngườiii

**Comment by YDinhC06** [comment]
你好

**Comment by YDinhC06** [comment]
T làm câu 1 b5 với câu 4 b6 nhe

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Hello mọi ngườiii

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Tui làm câu 1 bài 5 với câu 2 bài 6 nhe 😘😘

**Comment by duyanhthptphunhuan** [comment]
sin chaoooo mng

**Comment by duyanhthptphunhuan** [comment]
tui làm câu 1 2 bài 5 nha

**Comment by trthann** [comment]
@ThaiDungthaythayHiendeptrailamhihi  bài 6 hong cóa c2 m ơiii

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
> @ThaiDungthaythayHiendeptrailamhihi bài 6 hong cóa c2 m ơiii

À ý t là câu 4 :)

**Comment by trthann** [comment]
cả nhà iu tranh thủ làm nhaaa

**Comment by trthann** [comment]
nếu câu trả lời nào dài quá k chèn vào column được thì mng gửi qua discussion nha

**Comment by YDinhC06** [comment]
Z để sau khi coá câu 3 t mới làm câu 4 đc nha

**Comment by trthann** [comment]
uki luôn

**Comment by PhuongNgannLe** [comment]
hic t làm câu 1 bài 5 với câu 3 bài 6 nha

**Comment by YDinhC06** [comment]
Tui gửi trc câu 1 bài 5 nha
Có 3 loại ngôn ngữ lập trình:

1. Ngôn ngữ máy
Ví dụ ngôn ngữ máy:
01100001 : a
01100010 : b
01000001 : A
- Ưu điểm: cho phép khai thác triệt để và tối ưu khả năng của máy.
- Nhược điểm:
+ Ngôn ngữ phức tạp, phụ thuộc nhiều vào phần cứng, chương trình viết mất nhiều công sức, cồng kềnh và khó hiệu chỉnh.
+ Ngôn ngữ này không thích hợp với số đông người lập trình

2. Hợp ngữ
Một số lệnh:
INPUT: Nhập giá trị
ADD: Phép cộng
SUB: Phép trừ
DIV: Phép chia
- Ưu điểm: 
+ Ngôn ngữ kết hợp ngôn ngữ máy với ngôn ngữ tự nhiên của con người
- Nhược điểm của hợp ngữ:
+ Còn phức tạp, phụ thuộc vào nhiều loại máy
+ Chỉ thích hợp với các nhà lập trình chuyên nghiệp
+ Để chương trình viết bằng hợp ngữ thực hiện được trên máy tính, nó cần được dịch ra ngôn ngữ máy bằng chương trình hợp dịch

3. Ngôn ngữ bậc cao
Một số ngôn ngữ bậc cao: Turbo Pascal, Visual Basic, Java, Delphi, C++...
-Ưu điểm:
+ Gần ngôn ngữ tự nhiên
+ Tính độc lập cao
+ Ít phụ thuộc vào loại máy, chương trình viết ngắn gọn, dễ hiểu, dễ nâng cấp
-Nhược điểm:
+ Muốn máy hiểu được phải chuyển sang ngôn ngữ máy

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
T cũng làm câu 1 bài 5 nha !!
 Có 3 loại ngôn ngữ lập trình :
   - Ngôn ngữ máy :
    + Ưu điểm : Chương trình được viết bằng ngôn ngữ máy, ta có thể khai thác triệt để các đặc điểm phần cứng của máy tính.
    + Nhược điểm : 
       • Phải nhớ 1 cách máy móc các dòng số không gợi ý nghĩa của lệnh.
       • Dùng nhiều câu lệnh để diễn tả chi tiết các thao tác của thuật toán.
       • Khó hiểu, khó biểu diễn.
    - Hợp ngữ :
      + Ưu điểm : 
       • Khai thác triệt để tính năng phần cứng.
       • Cho phép người dùng lập được 1 số từ ( thường là viết tắt các từ tiếng Anh ) đêt thực hiện các lệnh cần thực hiện trên thanh ghi.
      + Nhược điểm : 
        • Đã thuận lợi cho các nhà lập trình chuyên nghiệp nhưng chưa thích hợp với số đông người lập trình.
        • Để máy tính hiểu cần có chương trình hợp dịch để chuyển hợp ngữ sang ngôn ngữ máy.
     - Ngôn ngữ bậc cao : 
       + Ưu điểm : 
         • Ngôn ngữ lập trình bậc cao sử dụng các câu lệnh : 
            * Được viết gần với ngôn ngữ tự nhiên hơn.
            * Có tính độc lập cao.
            * Ít phụ thuộc vào các loại máy cụ thể.
       + Nhược điểm : 
          • Ngôn ngữ bậc cao cần có 1 chương trình dịch những chương trình bằng ngôn ngữ này sang ngôn ngữ máy.

**Comment by duyanhthptphunhuan** [comment]
Câu 1 Bài 5
Có 3 loại ngôn ngữ lập trình
-Ngôn ngữ máy
Ưu điểm
+Khai thác triệt để tính năng phần mềm của máy tính
+Có thể trực tiếp hiểu được, không cần chương trình dịch.
Nhược điểm
+Khó hiểu, khó nhớ
+Dùng nhiều câu lệnh để diễn tả chi tiết các thao tác của thuật toán.
-Hợp ngữ
Ưu điểm
+Khai thác triệt để tính năng của phần cứng
Nhược điểm
+Chỉ thuận lợi với những nhà lập trình chuyên nghiệp nhưng chưa thích hợp với số đông người lậ trình.
+Phải có chương trình hợp dịch để chuyển hợp ngữ sang ngôn ngữ máy để máy tính có thể hiểu được.
-Ngôn ngữ bậc cao
Ưu điểm
+Chương trình dễ viết, dễ hiểu hơn ngôn ngữ máy.
+Được so sánh gần giống nhất với ngôn ngữ tự nhiên
+Có tính độc lập cao
Nhược điểm
+Chương trình còn cồng kềnh, phức tạp. Khó nhớ , còn phụ thuộc vào loại máy.
Câu 2 Bài 5
3 trong số những ngôn ngữ bậc cao mà em thích nhất là:
+Ngôn ngữ lập trình Javascript vì ngôn ngữ này xuất hiện lần đầu vào năm 1995 và đặt nền móng cho các trang web động trong web hiện đại. Đồng thời đây là một trong những ngôn ngữ lập trình phổ biến nhất hiện nay.
+Ngôn ngữ lập trình Python vì đây là ngôn ngữ rất đa dạng đồng thời là sự lựa chọn ưu tiên để tự động hóa các tác vụ( đặc biệt là trong ứng dụng phần mềm 3D).
+Ngôn ngữ lập trình Scratch vì đây là phần mềm miễn phí và rất được ưa chuộng trong lĩnh vực giáo dục và còn có kho lưu trữ rất lớn lên tới 20 triệu dự án với người dùng tăng lên mỗi tháng.

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 6 dựa trên câu 5 ví dụ 3 : 
- Cách liệt kê : 
B1) Nhập M,N 
B2) Nếu M= N thì lấy giá trị chung này làm UCLN rồi chuyển đến bược năm
B3)Nếu M > N thì M <- M-N rồi quay lại bước 2 
B4) N <- N-M rồi quay lại bước 2 
B5) Đưa ra kết quả UCLN rồi kết thúc

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 6 dựa trên câu 5 ví dụ 2 : 
 - Cách liệt kê : 
   + Bước 1 : Nhập số nguyên A
   + Bước 2 : Nếu A=0 thì quay lại Bước 1, ngược lại thì sang bước 3.
   + Bước 3 : Nếu A chia hết cho 2 thì A là số chẵn, ngược lại thì ( nếu không thì ) A là số lẻ, rồi qua bước 4.
   + Bước 4 : Xuất kết quả ra màn hình và kết thúc.
 - Cách vẽ bằng sơ đồ khối có gì ib mess hay sao đó nha.
     Cre : Tho Huynh

**Comment by ThaiDungthaythayHiendeptrailamhihi** [comment]
Câu 6 dựa trên câu 5 ví dụ 1 :
 - Cách liệt kê : 
  + Bước I. Nhập ba số a, b, c;

  + Bước 2 : d ← (b*b - 4*a*c);

  +  Bước 3 : Nếu d < 0 thì đưa ra thông báo phương trình vô nghiệm rồi kết thúc;
                       Nếu d = 0 thì đưa ra thông báo phương trình có một nghiệm và tính nghiệm x = -b/(2*a), rồi kết thúc;
                       Nếu d> 0 thì đưa ra thông báo phương trình có hai nghiệm phân biệt, tính nghiệm x1= (-b + -√d) / (2*a) và x2 = (-b - √ d ) / (2*a), rồi kết thúc;
  - Cách mô tả thuật toán theo sơ đồ khối : 
   Ib mess hay gửi lên đây á

**Comment by YDinhC06** [comment]
Câu 2 bài 6
Bài 1 Cho phương trình ax^2 + bx + c = 0 . Tìm nghiệm của phương trình
Cách liệt kê:
-bước 1: nhập 3 số a,b,c vào (với a≠0)
-bước 2: tính giá trị b^2
-bước 3: tính giá trị 4ac
-bước 4: ▵= bước 2 - bước 3
-bước 5: 
Th1: ▵>0 phương trình có 2 nghiệm
Th2: ▵<0 phương trình vô nghiệm
Th3: ▵=0 phương trình có nghiệm kép
-bước 6: 
Th1: x1=(-b-√▵)/2a; x2=(-b+√▵)/2a
Th2: vô nghiệm
Th3: x1=x2=-b/2a


Bài 2 Cho số nguyên dương A. Hãy tính A là số chẵn hay số lẻ
-bước 1: lấy A chia cho 2 
-bước 2: nếu ra số dư=0-->A là số chẵn,
kết thúc thuật toán
nếu ra số dư≠0-->A là số lẻ, kết thúc thuật toán


Bài 3 : Cho 2 số nguyên dương A và B . Hãy tính ước chung lớn nhất của 2 số A,B đó
-Bước 1: Nhập M, N;
-Bước 2: Nếu M = N đưa ra ƯCLN(M,N)=M; Kết thúc
-Bước 3: Nếu M > N thì M ←M – N rồi quay lại bước 2;
-Bước 4: N ←N – M rồi quay lại bước 2
https://hocz.net/bai-hoc-tin-hoc-10/tin-hoc-10-bai-6-giai-bai-toan-tren-may-tinh_10533.html

**Comment by YDinhC06** [comment]
Bài 3 sơ đồ khối

**Comment by PhuongNgannLe** [comment]
Câu 1 Bài 5:
Ngôn ngữ lập trình chính gồm có 3 loại: Ngôn ngữ máy, hợp ngữ và ngôn ngữ bậc cao
a. Ngôn ngữ máy
Ưu điểm:
Là ngôn ngữ duy nhất máy tính có thể trực tiếp hiểu và thực hiện, cho phép khai thác triệt để và tối ­ưu khả năng của máy.
Nhược điểm:
Ngôn ngữ phức tạp, phụ thuộc nhiều vào phần cứng, ch­ương trình viết mất nhiều công sức, cồng kềnh và khó hiệu chỉnh.
Không thích hợp với số đông ng­ười lập trình.
b. Hợp ngữ
Ưu điểm:
Hợp ngữ cho phép người lập trình sử dụng một số từ (thường là các từ tiếng Anh viết tắt) để thể hiện các lệnh cần thực hiện.
Cho phép khai thác triệt để tính năng phần cứng.
Nhược điểm:
Thuận lợi cho các nhà lập trình chuyên nghiệp nhưng chưa thích hợp với số đông người lập trình.
Để máy tính hiểu cần có chương trình hợp dịch để chuyển hợp ngữ sang ngôn ngữ máy.
c. Ngôn ngữ bậc cao
Ưu điểm:
Dễ hiểu, dễ chỉnh sửa, tính độc lập cao.
Để máy tính hiểu được, cần phải có chương trình dịch để chuyển từ ngôn ngữ bậc cao sang ngôn ngữ máy.
Một số ngôn ngữ lập trình bậc cao: Pascal, C, Java, …
https://hoc24.vn/ly-thuyet/bai-5-ngon-ngu-lap-trinh.3225

**Comment by PhuongNgannLe** [comment]
Câu 3 Bài 6:
Việc giải bài toán trên máy tính không giống như việc giải quyết vấn đề ngoài đời thực . Tại vì máy tính chỉ có thể xử lý các bài toán đã được lập trình sẵn các bước , có sẵn thuật toán và sử dụng ngôn ngữ riêng của máy tính.
Bài 1 : Cho phương trình ax^2 + bx + c = 0 . Tìm nghiệm của phương trình
Bài 2 : Cho số nguyên dương A. Hãy tính A là số chẵn hay số lẻ
Bài 3 : Cho 2 số nguyên dương A và B . Hãy tính ước chung lớn nhất của 2 số A , B đó
